version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
        docker:
          - image: cypress/base:latest
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
              name: Build the app
              command: npm run build
  deploy-to-render-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Staging
          command: |
            echo "Deploying to Render Staging"
            curl $RENDER_STAGING_DEPLOYHOOK
  deploy-to-render-production:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to Render Production
          command: |
            echo "Deploying to Render production"
            curl $RENDER_PRODUCTION_DEPLOYHOOK

workflows:
  run-tests-and-deploy-to-staging-then-production:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-render-staging:
          requires:
            - run-component-tests
          filters:
            branches:
              only: main
      - deploy-to-render-production:
          requires:
            - deploy-to-render-staging
          filters:
            branches:
              only: main